easy_admin:
    entities:
        Date:
            class: App\Entity\Date
            label: Dates
            # ... Autres configurations ...
            list:
                actions:
                    - { name: 'delete' }
                    - { name: 'generate_dates', label: 'Générer Dates', icon: 'plus' }

            edit: # Ajoutez cette section pour désactiver l'action Edit
                disabled: true
            new:
                disabled: true
        Inscription:
            class: App\Entity\Inscription
            label: Inscriptions
            list:
                # ...

                # Ajoutez des champs de l'entité Paiement
                - { property: 'paiement.moyen', label: 'Moyen de Paiement' }
                - { property: 'paiement.quantite', label: 'Quantité' }
                - { property: 'paiement.amount', label: 'Montant' }