controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

date_list:
    path: '/admin/date/list'
    controller: 'App\Controller\Admin\DateCrudController::index'
    methods: ['GET']